/** 
 * \file HsNavCommon.h
 *
 * Common defines shared between HsNav.h (#include for 68K programs)
 * and HsNavArm.h (#include for ARM programs).  The contents of this
 * file will all be integrated into the OS headers of PalmOS 6.x.  
 * The definitions are therefore preceded by the OS header file into
 * which they will be integrated.
 *
 * \license
 * 
 * Copyright (c) 2002 Handspring Inc., All Rights Reserved
 *
 * $Id:$
 *
 ****************************************************************/

#ifndef	  __HS_NAV_COMMON_H__
#define	  __HS_NAV_COMMON_H__


#include <Bitmap.h>	// for RGBColorType

#if 0
#pragma mark -------- HS-Specific -------------
#endif

#define	hsNavFocusRingWidth			  3
#define	hsNavFocusRingNoExtraInfo	  ((Int16)0xFFFF)


enum HsNavFocusColorEnumTag
{
  hsNavFocusColorInsideBottomRightRing = 0,
  hsNavFocusColorInsideTopLeftRing = 1,
  hsNavFocusColorMiddleRing = 2,
  hsNavFocusColorOutsideRing = 3,
  hsNavFocusColorSecondaryHighlight = 4
};
typedef UInt16 HsNavFocusColorEnum;


enum HsNavFocusRingStyleEnumTag
{
  hsNavFocusRingStyleObjectTypeDefault = 0,
  hsNavFocusRingStyleSquare = 1,
  hsNavFocusRingStyleRound = 2
};
typedef UInt16 HsNavFocusRingStyleEnum;


#if 0
#pragma mark -------- Incs:Core:UI:UIResources.h -------------
#endif

#define formNavRscType                      'fnav'


#if 0
#pragma mark -------- Incs:Core:System:TextMgr.h ---------------
#endif

//*********************************************************
// Macro for detecting if character is a rocker character
//*********************************************************

// <c> is a rocker key if the event modifier <m> has the command bit set
// and <c> is in the proper range
#define	TxtCharIsRockerKey(m, c)	((((m) & commandKeyMask) != 0) && \
									((((c) >= vchrRockerUp) && ((c) <= vchrRockerCenter))))


#if 0
#pragma mark -------- Incs:Core:CoreTraps.h ----------------
#endif

//*********************************************************
// Selector definitions for Navigation API functions
//*********************************************************

#define sysTrapNavSelector						0xA46F

#define NavSelectorFrmCountObjectsInNavOrder	0x0
#define NavSelectorFrmGetNavOrder            	0x1
#define NavSelectorFrmSetNavOrder           	0x2
#define NavSelectorFrmGetNavEntry				0x3
#define NavSelectorFrmSetNavEntry	       		0x4
#define NavSelectorFrmGetNavState		  		0x5
#define NavSelectorFrmSetNavState				0x6


#if 0
#pragma mark ------- Incs:Core:System:ErrorBase.h --------
#endif

//*********************************************************
// Error class and codes for UI Library
//*********************************************************

#define uilibErrorClass             0x3A00  // UI Library (Forms, Controls, etc)

#define uilibErrInvalidParam		(uilibErrorClass | 1)
#define uilibErrCurrentFocusInvalid	(uilibErrorClass | 2)
#define	uilibErrObjectFocusModeOff	(uilibErrorClass | 3)
#define uilibErrObjectNotFound		(uilibErrorClass | 4)
#define uilibErrNoNavInfoForForm	(uilibErrorClass | 5)
#define uilibErrInvalidFocusObject	(uilibErrorClass | 6)


#if 0
#pragma mark -------- Incs:Core:UI:Navigation.h -----------
#endif

//*********************************************************
// Nav Flags (used with navFlags field of FrmNavHeaderType)
//*********************************************************
typedef UInt32	FrmNavHeaderFlagsType;

#define	kFrmNavHeaderFlagsObjectFocusStartState		  0x00000001
#define	kFrmNavHeaderFlagsAppFocusStartState		  0x00000002
#define kFrmNavHeaderFlagsAutoGenerated				  0x80000000

#define kFrmNavHeaderFlagsStartStateMask			  0x00000003
#define	kFrmNavHeaderFlagsDefaultStartStateValue	  0x00000000
#define	kFrmNavHeaderFlagsObjectFocusStartStateValue  0x00000001
#define	kFrmNavHeaderFlagsAppFocusStartStateValue	  0x00000002
#define kFrmNavHeaderFlagsInvalidStartStateValue	  0x00000003


//*********************************************************
// Object Flags (used with objectFlags field of
//	FrmNavOrderEntryType)
//*********************************************************
typedef UInt16	FrmNavObjectFlagsType;

#define kFrmNavObjectFlagsSkip					0x0001
#define	kFrmNavObjectFlagsForceInteractionMode	0x0002
#define	kFrmNavObjectFlagsIsBigButton			0x8000


//*********************************************************
// Nav State Flags (used with stateFlags parameter of 
//	FrmGetNavState and FrmSetNavState API functions)
//*********************************************************
typedef UInt32	FrmNavStateFlagsType;

#define kFrmNavStateFlagsInteractionMode		0x00000001
#define kFrmNavStateFlagsObjectFocusMode		0x00000002


//*********************************************************
// The current version of the navigation structures
//  (FrmNavOrderEntryType and FrmNavHeaderType)
//*********************************************************
#define kFrmNavInfoVersion						1


#if 0
#pragma mark --------  Public Structures   ----------------
#endif

//*********************************************************
// Structures used with Navigation API functions
//*********************************************************

typedef struct FrmNavOrderEntryTag
{
    UInt16				  objectID;
    FrmNavObjectFlagsType objectFlags;
    UInt16				  aboveObjectID;
    UInt16				  belowObjectID;
} FrmNavOrderEntryType;


typedef struct FrmNavHeaderTag
{
    UInt16				  version;				  // This is version 1
	UInt16				  numberOfObjects;
	UInt16				  headerSizeInBytes;	  // 20 for the version 1 structure
	UInt16				  listElementSizeInBytes; // 8 for the version 1 structure
    FrmNavHeaderFlagsType navFlags;
    UInt16				  initialObjectIDHint;
    UInt16				  jumpToObjectIDHint;
    UInt16				  bottomLeftObjectIDHint;
	UInt16				  padding1;
} FrmNavHeaderType;

#endif	  // __HS_NAV_COMMON_H__


